//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace glovia_obic7.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqliteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqliteResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("glovia_obic7.Infrastructure.SqliteResource", typeof(SqliteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   接続準備時に予期せぬエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionException {
            get {
                return ResourceManager.GetString("ConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DBの接続に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectionFail {
            get {
                return ResourceManager.GetString("ConnectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQLの実行ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateCommandFail {
            get {
                return ResourceManager.GetString("CreateCommandFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   渡された引数の型が処理できない形式です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DbtypeException {
            get {
                return ResourceManager.GetString("DbtypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切断時に予期せぬエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisconnectionException {
            get {
                return ResourceManager.GetString("DisconnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT after FROM [company] where base = ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetCompanyCodeByBase {
            get {
                return ResourceManager.GetString("SqlGetCompanyCodeByBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT kbn FROM [company] where base = ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetCompanyKbnByBase {
            get {
                return ResourceManager.GetString("SqlGetCompanyKbnByBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT base,after,name FROM [company] where deleted = 0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetCompanyList {
            get {
                return ResourceManager.GetString("SqlGetCompanyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT code FROM [convert_code] where key = ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetConvertCodeCodeByKey {
            get {
                return ResourceManager.GetString("SqlGetConvertCodeCodeByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT system FROM [convert_code] where key = ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetConvertCodeSystemByKey {
            get {
                return ResourceManager.GetString("SqlGetConvertCodeSystemByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT key,code,name FROM [convert_code] where deleted = 0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetConvertList {
            get {
                return ResourceManager.GetString("SqlGetConvertList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT key,target1,target2,target3,target4 FROM [convert_type] where key = ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetConvertTypeByKey {
            get {
                return ResourceManager.GetString("SqlGetConvertTypeByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT key,target1,target2,target3,target4 FROM [convert_type] where deleted = 0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetConvertTypeList {
            get {
                return ResourceManager.GetString("SqlGetConvertTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT code FROM [s_denpyo_kind] where account = ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetDenpyoKindCodeByAccount {
            get {
                return ResourceManager.GetString("SqlGetDenpyoKindCodeByAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT code FROM [s_denpyo_kind] where account is null に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetDenpyoKindCodeDefault {
            get {
                return ResourceManager.GetString("SqlGetDenpyoKindCodeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT LAST_INSERT_ROWID() に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetLastInsertRowId {
            get {
                return ResourceManager.GetString("SqlGetLastInsertRowId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT code FROM [s_torihiki_kbn] where expense_account = ? and payable_account = ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetSaimuTorihikiKbnCode {
            get {
                return ResourceManager.GetString("SqlGetSaimuTorihikiKbnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT code from [s_torihiki_kbn] where expense_account is null and payable_account is null に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetSaimuTorihikiKbnCodeDefault {
            get {
                return ResourceManager.GetString("SqlGetSaimuTorihikiKbnCodeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT code FROM [system_code] where key = ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlGetSystemCodeByKey {
            get {
                return ResourceManager.GetString("SqlGetSystemCodeByKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT value FROM [col_hojo] where code = ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlIsHojoByCode {
            get {
                return ResourceManager.GetString("SqlIsHojoByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT code FROM [col_torihiki] where code = ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlIsTorihikiByCode {
            get {
                return ResourceManager.GetString("SqlIsTorihikiByCode", resourceCulture);
            }
        }
    }
}
