//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace glovia_obic7.Services {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("glovia_obic7.Services.ServiceResource", typeof(ServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   backup_base_path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigBackupPath {
            get {
                return ResourceManager.GetString("ConfigBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyyMMdd_HHmmss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigBackupPathDateFormat {
            get {
                return ResourceManager.GetString("ConfigBackupPathDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   output_path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigOutputPath {
            get {
                return ResourceManager.GetString("ConfigOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigPathEndString {
            get {
                return ResourceManager.GetString("ConfigPathEndString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   search_path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigSourcePath {
            get {
                return ResourceManager.GetString("ConfigSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyyMMdd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvertGloviaDateFormat {
            get {
                return ResourceManager.GetString("ConvertGloviaDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (CMS|USE).dat$ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListupMatchOtherPattern {
            get {
                return ResourceManager.GetString("ListupMatchOtherPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (ACN|HAN)_(KEI|NYUU|SIIRE|URI|ZAI).dat$ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListupMatchPattern {
            get {
                return ResourceManager.GetString("ListupMatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListupSearchPattern {
            get {
                return ResourceManager.GetString("ListupSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputDateFormat {
            get {
                return ResourceManager.GetString("OutputDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sjis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputEncod {
            get {
                return ResourceManager.GetString("OutputEncod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}{1}_{2}.csv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputfileTemplate {
            get {
                return ResourceManager.GetString("OutputfileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shift_jis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputStreamEncod {
            get {
                return ResourceManager.GetString("OutputStreamEncod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParamaterName_Code {
            get {
                return ResourceManager.GetString("ParamaterName_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACN_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prefix_ARCANE {
            get {
                return ResourceManager.GetString("Prefix_ARCANE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HAN_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prefix_JFLA {
            get {
                return ResourceManager.GetString("Prefix_JFLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prefix_REPLACE {
            get {
                return ResourceManager.GetString("Prefix_REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   債務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SAIMU {
            get {
                return ResourceManager.GetString("SAIMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   手形 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TEGATA {
            get {
                return ResourceManager.GetString("TEGATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TORIHIKI {
            get {
                return ResourceManager.GetString("TORIHIKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   財務 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZAIMU {
            get {
                return ResourceManager.GetString("ZAIMU", resourceCulture);
            }
        }
    }
}
