//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace glovia_obic7.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessage() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("glovia_obic7.Resources.LogMessage", typeof(LogMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ファイル出力先情報が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIG_NO_OUTPUTPATH {
            get {
                return ResourceManager.GetString("CONFIG_NO_OUTPUTPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル検索先情報が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIG_NO_SEARCHPATH {
            get {
                return ResourceManager.GetString("CONFIG_NO_SEARCHPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップ先が存在していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIG_NOT_EXIST_BACKUPPATH {
            get {
                return ResourceManager.GetString("CONFIG_NOT_EXIST_BACKUPPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル出力先が存在していません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIG_NOT_EXIST_OUTPUTPATH {
            get {
                return ResourceManager.GetString("CONFIG_NOT_EXIST_OUTPUTPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gloviaデータ基本パス={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIG_SHOW_SEARCHPATH {
            get {
                return ResourceManager.GetString("CONFIG_SHOW_SEARCHPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ変換処理を終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONVERT_END {
            get {
                return ResourceManager.GetString("CONVERT_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重大エラーが発生したため処理を中断します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONVERT_FATAL_ERROR {
            get {
                return ResourceManager.GetString("CONVERT_FATAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換パターン不明のため、{0}の処理をスキップします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONVERT_MODE_UNKNOWN {
            get {
                return ResourceManager.GetString("CONVERT_MODE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ変換処理を開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONVERT_START {
            get {
                return ResourceManager.GetString("CONVERT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ変換処理を中止します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONVERT_STOP {
            get {
                return ResourceManager.GetString("CONVERT_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル変換の終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_CONVERSION_END {
            get {
                return ResourceManager.GetString("FILE_CONVERSION_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換対象のプロセスが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_CONVERSION_NO_PROCESS {
            get {
                return ResourceManager.GetString("FILE_CONVERSION_NO_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しているためファイル出力を行いません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_CONVERSION_SAVE_SKIP {
            get {
                return ResourceManager.GetString("FILE_CONVERSION_SAVE_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル変換の開始　対象ファイル={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_CONVERSION_START {
            get {
                return ResourceManager.GetString("FILE_CONVERSION_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力フォルダに展開中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_COPY_ABORT {
            get {
                return ResourceManager.GetString("FILE_COPY_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成したファイルを出力フォルダに展開しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_COPY_END {
            get {
                return ResourceManager.GetString("FILE_COPY_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成したファイルを出力フォルダに展開します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_COPY_START {
            get {
                return ResourceManager.GetString("FILE_COPY_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換処理[{0}] 対象ファイル={1} の処理を終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MODE_CONVERT_END {
            get {
                return ResourceManager.GetString("MODE_CONVERT_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理中に不正なエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MODE_CONVERT_EXCEPTION {
            get {
                return ResourceManager.GetString("MODE_CONVERT_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の処理をスキップします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MODE_CONVERT_SKIP {
            get {
                return ResourceManager.GetString("MODE_CONVERT_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換処理[{0}]の処理対象のため、{1}の処理を開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MODE_CONVERT_START {
            get {
                return ResourceManager.GetString("MODE_CONVERT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GLOVIAデータファイルが空です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MODE_SOURCEFILE_ENPTY {
            get {
                return ResourceManager.GetString("MODE_SOURCEFILE_ENPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GLOVIAデータファイルが正常に読み込めませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MODE_SOURCEFILE_UNREAD {
            get {
                return ResourceManager.GetString("MODE_SOURCEFILE_UNREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社コード[{0}]は不明な会社コードです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MODE_UNKNOWN_COMPANY_CODE {
            get {
                return ResourceManager.GetString("MODE_UNKNOWN_COMPANY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換後の出力データが存在しないため、ファイル[{0}]の出力を行いません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MODE_WRITE_EMPTY {
            get {
                return ResourceManager.GetString("MODE_WRITE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル出力中に不正なエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MODE_WRITE_EXCEPTION {
            get {
                return ResourceManager.GetString("MODE_WRITE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換後のファイルを[{0}]に出力しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MODE_WRITE_SUCCESS {
            get {
                return ResourceManager.GetString("MODE_WRITE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理対象のファイルがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_TARGET_FILES {
            get {
                return ResourceManager.GetString("NO_TARGET_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラム終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PROGRAM_END {
            get {
                return ResourceManager.GetString("PROGRAM_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラム起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PROGRAM_START {
            get {
                return ResourceManager.GetString("PROGRAM_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換モード={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHOW_CONVERT_MODE {
            get {
                return ResourceManager.GetString("SHOW_CONVERT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ファイル数={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHOW_TARGET_FILE_COUNT {
            get {
                return ResourceManager.GetString("SHOW_TARGET_FILE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力先準備中に例外エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_CLEAR_EXCEPTION {
            get {
                return ResourceManager.GetString("SYS_CLEAR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション構成ファイルの[{0}]のデータが正しくありません。値={1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_CONFIG_ERROR_VALUE {
            get {
                return ResourceManager.GetString("SYS_CONFIG_ERROR_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   環境情報取得中に例外エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_CONFIG_EXCEPTION {
            get {
                return ResourceManager.GetString("SYS_CONFIG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーション構成ファイルに [{0}] が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_CONFIG_SYS_NO_GET {
            get {
                return ResourceManager.GetString("SYS_CONFIG_SYS_NO_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換処理中に例外エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_CONVERSION_EXCEPTION {
            get {
                return ResourceManager.GetString("SYS_CONVERSION_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換処理メソッドの開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_CONVERSION_START {
            get {
                return ResourceManager.GetString("SYS_CONVERSION_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換処理[{0}]の処理中に例外エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_MODE_CONVERSION_EXCEPTION {
            get {
                return ResourceManager.GetString("SYS_MODE_CONVERSION_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モード[{0}]のファイル出力中に例外エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_MODE_WRITE_EXCEPTION {
            get {
                return ResourceManager.GetString("SYS_MODE_WRITE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ローカルＤＢに接続しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_SQL_CONNECT {
            get {
                return ResourceManager.GetString("SYS_SQL_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ローカルＤＢから切断しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SYS_SQL_DISCONNECT {
            get {
                return ResourceManager.GetString("SYS_SQL_DISCONNECT", resourceCulture);
            }
        }
    }
}
